### ISSUE TITLE
not so much of an issue , rather a clarification needed i think

### ISSUE THREAD

**Issue by fabiendostie** [petergridge/irrigation_component_V3#1]
when you say:
Copy the 'irrigation.yaml' file to the packages directory. Do you mean the folder that you created that is contained in the 
irrigation_component_3 folder named packages? because the irrigation.yaml is already in it? I must not understand something 
here see my picture:
<img width="363" alt="Screen Shot 2021-05-16 at 5 13 32 AM" src="https://user-images.githubusercontent.com/53846121/118392161-1bf48200-b606-11eb-86e4-4a229cda0274.png">

when you say:
or into configuration.yaml. Sample configuration:
Do you mean to copy-paste the contents into the main configuration.yaml inside the config folder or different one.
what is the sample configuration? i have been trying to understand for a few hours now but i am not.
I would really like to be able to use some components of your codes for my little gardening operation.
2 zones water basin 
drip irrigation system with messages to stop/start pumps when reservoir low/soil dry etc...
few mi floras, pressure sensor, water level sensor, switches all working well already 
The thing is that I am going to install solenoids next week and i would love to use some of your code but i want to understand what is it that you mean first.

Thanks for the help

i am puzzled a little

**Comment by petergridge** [comment]
**For the irrigation.yaml file**
In your HomeAssistant configuration.yaml you can setup you can add the following
```yaml
homeassistant:
  packages:  !include_dir_named packages
```
Then you can create a new directory 'packages' under the config directory. Copy the irrigation.yaml file into this new config\packages directory.

The alternative is to copy the entire contents of irrigation.yaml into the configuration.yaml found in the config directory.

**For the custom component setup**
Only copy the directory 'irrigationprogram' into the config\custom_components directory.

once you restart HA you can complete the setup following the instructions for Lovelace.

**Comment by fabiendostie** [comment]
I'll try that. Thank you!

**Comment by petergridge** [comment]
Issue Closed
