### ISSUE TITLE
recent error with start time

### ISSUE THREAD

**Issue by bsp9493** [petergridge/irrigation_component_V3#2]
Hi... can't seem to track this down, wondering if it's only me.

error log below

`Logger: custom_components.irrigationprogram.switch
Source: custom_components/irrigationprogram/switch.py:175 
Integration: Irrigation controller component (documentation, issues) 
First occurred: 12:38:50 PM (3 occurrences) 
Last logged: 12:38:50 PM

input_datetime.irrigation_program_1_start_time not found, check your configuration, program will not start
input_datetime.irrigation_program_2_start_time not found, check your configuration, program will not start
input_datetime.irrigation_program_3_start_time not found, check your configuration, program will not start`

**Comment by petergridge** [comment]
Hi, can you confirm that you have the input_datetime entities defined and active. You should be able to see them in the developer tools view.

you can also provide the yaml definitions for the irrigation object and related entities that you are using for me to review if you like.

**Comment by bsp9493** [comment]
Will do…

It’s strange, started doing this a couple of updates ago…

All working, just the datetime errors


yes, I have the 3 datetime setup in helpers (I have changed nothing) and using the most current versions of everything I believe.


Heading out of town for a few days, but have attached the yaml for now as well







thanx for the helps as always!!!

dave

**Comment by petergridge** [comment]
Hi Dave,

I can't see the yaml in this thread, can resend the file.

The check happens as the irrigation object loads, if the input_datetime entities have not loaded as yet that may be the cause. 

Cheers
Pete

**Comment by bsp9493** [comment]
attached again…




yes, that may be the issue as you noted - “entries may not have loaded…” as every thing seems to function just fine, except for the error messages.


d

**Comment by bsp9493** [comment]
Hi Peter… finally had some time to look at this again…



this is the error I get

This error originated from a custom integration.
Logger: custom_components.irrigationprogram.switch
Source: custom_components/irrigationprogram/switch.py:174 
Integration: Irrigation controller component (documentation <https://github.com/petergridge/irrigation_component_V3>, issues <https://github.com/petergridge/irrigation_component_V3/issues>) 
First occurred: 3:35:45 PM (3 occurrences) 
Last logged: 3:35:45 PM

input_datetime.irrigation_program_1_start_time not found, check your configuration, program will not start
input_datetime.irrigation_program_2_start_time not found, check your configuration, program will not start
input_datetime.irrigation_program_3_start_time not found, check your configuration, program will not start
error seems to come from switch.py

        """ Validate and Build a template from the attributes provided """
        if  hass.states.async_available(self._start_time):
            _LOGGER.error('%s not found, check your configuration, program will not start',self._start_time)



input_datetime helpers are currently  being created from the HA GUI instead of being manually created in the irrigation.yaml.  this is a recent change to try to track this down, but I still get the error regardless of how they are created.



irrigation.yaml below

irrigation:
#    input_datetime:
#      irrigation_program_1_start_time:
#        name: Start Time 1
#        has_date: false
#        has_time: true
#      irrigation_program_2_start_time:
#        name: Start Time 2
#        has_date: false
#        has_time: true
#      irrigation_program_3_start_time:
#        name: Start Time 3
#        has_date: false
#        has_time: true
    switch:
      - platform: irrigationprogram
        switches: 
          program_1:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_1_start_time
            run_days: input_select.irrigation_run_days
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run          
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
          program_2:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_2_start_time
            run_days: input_select.irrigation_run_days
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
                
          program_3:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_3_start_time
            run_days: input_select.irrigation_run_days
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
      - platform: template
        switches:
          dummy_1:
            value_template: "{{ is_state('switch.front_lawn_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_lawn_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_lawn_zone

          dummy_2:
            value_template: "{{ is_state('switch.front_door_shrubs_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_door_shrubs_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_door_shrubs_zone

          dummy_3:
            value_template: "{{ is_state('switch.front_street_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_street_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_street_zone
                
          dummy_5:
            value_template: "{{ is_state('switch.back_dripline_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.back_dripline_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.back_dripline_zone


    input_number:
# seasonal adjustment
      irrigation_adjust_run:
        name: water adjustment
        min: 0
        max: 1
        step: 0.05
        icon: mdi:water-pump-off
#front lawn
      irrigation_front_lawn_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_lawn_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_lawn_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#front door shrubs
      irrigation_front_door_shrubs_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_door_shrubs_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_door_shrubs_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#front street
      irrigation_front_street_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_street_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_street_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#back dripline
      irrigation_back_dripline_run:
        name: water
        min: 1
        max: 60
        step: 1
        icon: mdi:water
      irrigation_back_dripline_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_back_dripline_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat

    input_select:
    # Use either run days of Frequency they are mutually exclusive

      irrigation_run_days:
        name: Run Days
        options:
          - "['Wed','Sat']"
          - "['Sun','Thu']"
          - "['Mon','Fri']"
          - "['Tue','Sat']"
          - "['Sun','Wed']"
          - "['Mon','Thu']"
          - "['Tue','Fri']"
          - "['Mon','Wed','Fri']"
          - "['Mon','Tue','Wed','Thu','Fri','Sat','Sun']"
          - "['Sun','Wed','Fri']"

      irrigation_freq:
        name: Frequency
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"

    input_boolean:
      irrigation_on:
        name: Enable Irrigation

      irrigation_config:
        name: Show Configuration

      irrigation_ignore_rain_sensor:
        name: Ignore Rain Sensor
  
      dummy_switch_1:
      dummy_switch_2:
      dummy_switch_3:
      dummy_switch_5:
      dummy_rain_sensor:

    binary_sensor:
      - platform: template
        sensors:
          raining:
            device_class: moisture
            value_template: "{{ is_state('binary_sensor.meteobridge_is_raining', 'on') }}"
            icon_template: >-
              {% if is_state("binary_sensor.meteobridge_is_raining", "on") %}
                mdi:weather-pouring
              {% else %}
                mdi:weather-sunny
              {% endif %}





Thanx again for the help.

**Comment by petergridge** [comment]
Hi Dave,

You have an 'irrigation:' section in your yaml. Can you remove that section and try again. 

The 'irrigation:' is not required now that everything is defined as a platform of the switch object.

**Comment by bsp9493** [comment]
Not an irrigation section…

That is the name of my package…

Sorry bout that I’m using packages for all my custom yaml files

d

**Comment by bsp9493** [comment]
In main configuration.yaml

#packages

  ...homeassistant:
  !include_dir_merged_named packages/

Then in the packages directory, I have a sub directory named irrigation
Within that directory is a file named irrigation.yaml with the contents as in the other attachment. 

d

**Comment by bsp9493** [comment]
...Sorry, if last email is confusing… not at my computer…



Pictures should help:)





d

**Comment by petergridge** [comment]
Hi Dave,

I have updated the switch.py to move the validation of referenced objects until HASS has started. I think this will correct your problem.

please let me know how this goes.

Cheers
Pete

**Comment by bsp9493** [comment]
Thanx Pete!!!

Will update shortly and let you know:)



d

**Comment by bsp9493** [comment]
Ooohhhhh…that blew it up worse:(

I deleted my existing irrigationprogram directory and replaced with the new one from GitHub



Logger: homeassistant.config
Source: custom_components/irrigationprogram/switch.py:23 
Integration: irrigationprogram (documentation <https://github.com/petergridge/irrigation_component_V3>, issues <https://github.com/petergridge/irrigation_component_V3/issues>) 
First occurred: 8:50:06 AM (1 occurrences) 
Last logged: 8:50:06 AM

Platform error: switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 891, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 524, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 529, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/irrigationprogram/switch.py", line 23, in <module>
    from .const import (
ImportError: cannot import name 'ATTR_LAST_RAN' from 'custom_components.irrigationprogram.const' (/config/custom_components/irrigationprogram/const.py)

**Comment by petergridge** [comment]
Sorry Dave, Please try again.

**Comment by bsp9493** [comment]
no worries…

now I get a configuration error and homeassistant will NOT allow a restart.


The system cannot restart because the configuration is not valid: Platform error switch.irrigationprogram - cannot import name 'ATTR_LAST_RAN' from 'custom_components.irrigationprogram.const' (/config/custom_components/irrigationprogram/const.py)

**Comment by petergridge** [comment]
Can you check the const.py in your directory to confirm that the constant is defined in the version you have install for me.

**Comment by bsp9493** [comment]
I deleted my existing directory, saved the NEW files to my computer and copied the NEW directory obtained from GITHUB to my homeassistant machine.


this is the contents of the const.py file in the irrigationprogram directory.


DOMAIN                  = 'irrigationprogram'
SWITCH_ID_FORMAT        = 'switch' + '.{}'

ATTR_RAIN_SENSOR        = 'rain_sensor'
ATTR_IRRIGATION_ON      = 'irrigation_on'
ATTR_START              = 'start_time'
ATTR_IGNORE_RAIN_SENSOR = 'ignore_rain_sensor'
ATTR_IGNORE_RAIN_BOOL   = 'ignore_rain_bool'
ATTR_RUN_DAYS           = 'run_days'
ATTR_RUN_FREQ           = 'run_freq'
ATTR_FRIENDLY_NAME      = 'friendly_name'
ATTR_REMAINING          = 'remaining'
ATTR_REPEAT             = 'repeat'
ATTR_RUNTIME            = 'runtime'
ATTR_WAIT               = 'wait'
ATTR_WATER              = 'water'
ATTR_WATER_ADJUST       = 'water_adjustment'
ATTR_ZONES              = 'zones'
ATTR_ZONE               = 'zone'
ATTR_ICON               = 'icon'
ATTR_ICON_WATER         = 'icon_on'
ATTR_ICON_WAIT          = 'icon_wait'
ATTR_ICON_OFF           = 'icon_off'
ATTR_PROGRAMS           = 'programs'
ATTR_LAST_RAN           = 'last_ran'


CONST_ENTITY            = 'entity_id'
CONST_SWITCH            = 'switch'

DFLT_ICON_WATER         = 'mdi:water'
DFLT_ICON_WAIT          = 'mdi:timer-sand'
DFLT_ICON_OFF           = 'mdi:water-off'
DFLT_ICON               = 'mdi:fountain'
DFLT_ICON_RAIN          = 'mdi:weather-pouring'

**Comment by petergridge** [comment]
The attribute is definitely there.  I am stumped on this one, I will try and figure it out :/

**Comment by bsp9493** [comment]
ran vs run???  Just grasping at straws


ATTRS [ATTR_LAST_RAN] = self._last_run

**Comment by bsp9493** [comment]
something must have locked up in my homeassistant machine (a file lock, or something else strange).  I took a chance and powered down my raspberry pi to see if it would release and restart.

restart was successful
irrigationprogram loads

appears to be no errors!

d

**Comment by petergridge** [comment]
Great news! so what you should see now is if you forget to define one of the objects that you reference in defining the irrigation switches a warning/error will be generated.

Thanks for your help, it is much better to have fresh eyes look at your work to find defects that I miss.

**Comment by bsp9493** [comment]
No worries….

I appreciate the code and your help!

d
